#pragma once
#include "../Utils.h"

class Backend
{
public:
	bool Load();
	void Unload();
public:
	bool DirectXPresentHook();
	void UnloadDevices(bool renderTargetViewReset);
public:
	void LoadImGui(HWND window, ID3D11Device* device, ID3D11DeviceContext* context);
	void DrawImGui(ID3D11DeviceContext* context, ID3D11RenderTargetView* targetview);
	void UnloadImGui();
public:
	typedef long(__stdcall* presentVariable)(IDXGISwapChain*, UINT, UINT);
public:
	DXGI_SWAP_CHAIN_DESC m_gSwapChainDescription{};
	IDXGISwapChain* m_gSwapChain = nullptr;
	ID3D11Device* m_gDevice = nullptr;
	const D3D_FEATURE_LEVEL m_gFeatureLevels[2] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_0 };
	HWND m_gWindow = NULL;
	ID3D11DeviceContext* m_gPointerContext = nullptr;
	ID3D11RenderTargetView* m_gMainRenderTargetView = nullptr;
	ID3D11Texture2D* m_gPointerBackBuffer = nullptr;
public:
	WNDPROC m_goriginalWndProc;
	DXGI_SWAP_CHAIN_DESC m_gPresentHookSwapChain;
public:
	bool m_bOpenMenu = false; // no need to extern it, only used in Backend.cpp
    bool CursorClipped = false;
    bool Watermark = true;
    bool bgDim = true;

    enum Heads {
        General, Exploits, Account, Visuals, Misc
    };

    void SetCursorPosMiddle(HWND hWnd)
    {
        RECT rect;
        POINT center;
        GetClientRect(hWnd, &rect);
        center.x = rect.left + (rect.right - rect.left) / 2;
        center.y = rect.top + (rect.bottom - rect.top) / 2;
        ClientToScreen(hWnd, &center);
        SetCursorPos(center.x, center.y);
    }

    bool IsCursorNigga(HWND hWnd)
    {
        POINT curPos;
        GetCursorPos(&curPos);
        ScreenToClient(hWnd, &curPos);

        RECT nigRect;
        GetClientRect(hWnd, &nigRect);

        return PtInRect(&nigRect, curPos) != FALSE;
    }


	// functions and stuff
    uint64_t baseAddr = (uint64_t)GetModuleHandleA("GameAssembly.dll");

    bool KillAllCheck = false;
	bool AddCurrency = false;
    bool ActivatePass = false;
    bool AddCrowns = false;
	bool AddWeapon = false;
    bool AddWeapons = false;
	bool AddArmor = false;
	bool AddHats = false;
	bool AddBoots = false;
	bool AddCapes = false;
	bool AddMasks = false;
	bool AddVeteran = false;
    bool AddAArmor = false;
    bool AddHat = false;
    bool AddBoot = false;
    bool AddCape = false;
    bool AddMask = false;
	bool AddAvatars = false;
    bool AddShovels = false;
    bool AddGliders = false;
    bool AddTrails = false;
    bool AddVehicles = false;
    bool AddPets = false;
	bool AddGadgets = false;
	bool AddAllGadgets = false;
    bool XRay = false;
	bool Points = false;
	bool ESP = false;
	bool ArmorRegen = false;
	bool Bazooka = false;
	bool GrenadeLauncher = false;
	bool BulletExplode = false;
	bool Shotgun = false;
    bool Railgun = false;
    bool Harpoon = false;
    bool Flamethrower = false;
    bool FireImmunity = false;
    bool BleedingImmunity = false;
    bool ToxicImmunity = false;
    bool CoinDrop = false;
    bool MechShoot = false;
    bool ThreeCatSpam = false;
	bool InfiniteAmmo = false;
	bool DamageMulti = false;
	bool Godmode = false;
	bool xpSpoof = false;
    bool Level65 = false;
    bool xpAdder = false;
	bool Test = false;
	bool DoubleJump = false;
	bool Zoom = false;
    bool Ban = false; 
    bool Loadout = false;
    bool PolyMorpher = false;
    bool ChatSend = false;
    bool ChatLoop = false;
    char ChatInput[50] = "join .gg/Uw48gqKxNF for pg3d mods!";

	int xpSpoofInt = 1;
    int CrownsAmmount = 50;
    int AmmoAmmount = 0;
    int TestInt = 1;
	int CurrencyAmmount = 0;
	int CurrencyType = 0;
    bool PriceModifier = false;
    int ModifierAmmount = -1;
    int AddWeaponsBeginning = 1;
    int AddWeaponsEnd = 1;
    int ArmorType = 0;
	int GadgetLevel = 1;
	char WeaponInput[50] = "ultimatum";
	const char* CurrencyList[12] = {"GemsCurrency", "Coins", "ClanSilver", "ClanLootBoxPoints", "Coupons", "PixelPassCurrency", "RouletteAdsCurrency", "RouletteAdsSpin", "PixelBucks", "BattlePassCurrency", "CurrencyCompetitionTier1", "CurrencyCompetitionTier2" };
    const char* WeaponList[1341] = { "FirstPistol", "FirstShotgun", "UziWeapon", "Revolver", "Machingun", "MinersWeapon", "AK47", "Knife", "m16", "Eagle 1", "SPAS", "FAMAS", "Glock", "Shovel", "Hammer", "Beretta", "IronSword", "SteelAxe", "WoodenBow", "Chainsaw 2", "SteelCrossbow", "Hammer 2", "Mace 2", "Staff 2", "DoubleShotgun", "AlienGun", "m16_2", "Tree", "Fire_Axe", "SVD", "Barrett_2", "Uzi2", "Hunter_Rifle", "Bazooka", "railgun", "tesla", "grenade_launcher", "grenade_launcher2", "Bazooka_3", "GravityGun", "AUG", "katana_3", "bigbuddy", "Mauser", "Shmaiser", "Tompson", "Tompson_2", "basscannon", "SparklyBlaster", "CherryGun", "AK74", "FreezeGun", "3pl_Shotgun_3", "flowerpower_3", "Revolver4", "Scythe_3", "plazma_3", "plazma_pistol_2", "plazma_pistol_3", "Razer_3", "Flamethrower_3", "FreezeGun_0", "Minigun_3", "Barret_3", "LightSword_3", "Sword_2_3", "Staff 3", "DragonGun", "Bow_3", "Bazooka_2_3", "m79_3", "Red_Stone_3", "XM8_1", "PumpkinGun_1", "TwoBolters", "RayMinigun", "SignalPistol", "AutoShotgun", "TwoRevolvers", "SnowballGun", "SnowballMachingun", "HeavyShotgun", "Solar_Ray", "Water_Pistol", "Solar_Power_Cannon", "Water_Rifle", "Needle_Throw", "Valentine_Shotgun", "Carrot_Sword", "Easter_Bazooka", "RailRevolverBuy", "Assault_Machine_GunBuy", "Impulse_Sniper_RifleBuy", "Autoaim_RocketlauncherBuy", "PX-3000", "Sunrise", "Bastion", "DualHawks", "StormHammer", "Badcode_gun", "ElectroBlastRifle", "PlasmaShotgun", "Devostator", "Dark_Matter_Generator", "Hydra", "TacticalBow", "FutureRifle", "RapidFireRifle", "DualUzi", "LaserDiscThower", "Tesla_Cannon", "Photon_Pistol", "Fire_orb", "Hand_dragon", "Alligator", "Hippo", "Alien_Cannon", "Alien_Laser_Pistol", "Dater_Flowers", "Dater_DJ", "Dater_Arms", "Dater_Bow", "FriendsUzi", "Alien_rifle", "VACUUMIZER", "Fireworks_Launcher", "Shotgun_Pistol", "Range_Rifle", "Pit_Bull", "Tiger_gun", "Balloon_Cannon", "Mech_heavy_rifle", "Shuriken_Thrower", "BASIC_FLAMETHROWER", "snowball", "MysticOreEmitter", "Laser_Crossbow", "Nutcracker", "SPACE_RIFLE", "Icicle_Generator", "PORTABLE_DEATH_MOON", "Candy_Baton", "Hockey_stick", "Space_blaster", "mp5_gold_gift", "Dynamite_Gun_1", "Dual_shotguns_1", "Antihero_Rifle_1", "HarpoonGun_1", "Red_twins_pistols_1", "Toxic_sniper_rifle_1", "NuclearRevolver_1", "NAIL_MINIGUN_1", "DUAL_MACHETE_1", "Fighter_1", "Gas_spreader", "LaserBouncer_1", "magicbook_fireball", "magicbook_frostbeam", "magicbook_thunder", "TurboPistols_1", "Laser_Bow_1", "loud_piggy", "Trapper_1", "chainsaw_sword_1", "dark_star", "toy_bomber", "zombie_head", "mr_squido", "RocketCrossbow", "spark_shark", "power_claw", "zombie_slayer", "AcidCannon", "frank_sheepone", "Ghost_Lantern", "Semiauto_sniper", "Chain_electro_cannon", "Barier_Generator", "Demoman", "charge_rifle", "minigun_pistol", "bad_doctor_1", "dual_laser_blasters", "toxic_bane", "Charge_Cannon", "Heavy_Shocker", "ruler_sword_1", "pencil_thrower_1", "napalm_cannon", "sword_of_shadows", "dracula", "xmas_destroyer", "santa_sword", "snow_storm", "heavy_gifter", "bell_revolver", "elfs_revenge", "photon_sniper_rifle", "subzero", "mercenary", "laser_spear", "nunchuks", "double_dragon", "magicbook_love", "casanova", "romeo_and_juliette", "Q_grenade_launcher", "Q_machine_gun", "Q_electrogun", "Q_railgun", "Q_rocket_launcher", "Q_shotgun", "Q_plasma_gun", "Q_chopper", "Q_BFG", "Blade_of_Justice", "lab_eight_barrel_shotgun", "Tactical_tomahawk", "Masterpiece_musket", "Executioner", "Serious_argument", "lab_piranha", "lab_oneshot", "lab_machinegun", "lab_combatyoyo", "lab_orbital_pistol", "Defender_of_the_law", "fidget_thrower", "festive_bazooka", "thunderer", "bomber_slingshot", "future_sniper_rifle", "beast", "invader", "core_sword", "hedgehog", "third_eye", "eraser", "excalibur", "poseidon_trident", "reaper", "void_ray_rifle", "black_mamba", "chip_sword", "vampire_hunter", "mountain_wolf", "hurricane", "dino_slayer", "soulstone", "electrosphere", "prototype_s", "frozen_dragon", "special_agent", "Power_Fists", "VerticalShotgun", "astral_bow", "zeus_chain_ sword", "music_lover", "veteran", "mini_alien_spaceship", "flag_keeper", "leaders_sword", "last_christmas", "laser_assistant", "dual_cryo_pistols", "automatic_decorator", "elder_force_saber", "Champion_Mercenary", "champion_peacemaker", "adamant_laser_cannon", "Adamant_Revolver", "adamant_spear", "champion_electric_arc", "adamant_sniper_rifle", "Anti-Champion_Rifle", "Champion_Solar_Cannon", "Adamant_Bomber", "sharp_snowflake", "little_cthulhu", "magicbook_curse_spell", "airblade_spell", "magicbook_poison_spell", "magicbook_earth_spikes_spell", "magicbook_shadow_spell", "Dragon_King", "angry_pumpkin", "Steam_Knuckes", "electro_blast_pistol", "wyvern_sniper", "hero", "sly_avenger", "bright_reflector", "sakura", "deadly_beat", "killer_whale", "renegade", "demon_sword", "bolters2", "Stormtrooper_Exoskeleton", "Sniper_Exoskeleton", "demolition_exosceleton", "hitman_exoskeleton", "berserk_exoskeleton", "engineer_exoskeleton", "death_claws", "Eva", "space_desinsector", "mega_gun", "laser_revolver", "Sword_and_Shield", "last_samurai", "manga_gun", "anime_schtye", "nitrogen_spreader", "future_police_rifle", "stakegun", "alive_blaster", "plasma_cutter", "good_doctor", "devastator", "supercharged_rifle", "archangel", "manticore", "soul_thief", "multitaskers", "yin_yang", "last_hope", "Jet_hammer", "energy_drill", "Spender", "graviton", "acid_pistol", "Rhino", "antique_pistol", "lava_thrower", "Inventors_Rifle", "vandals", "revolver_sniper_rifle", "captain", "void_energy_pistol", "destruction_system", "circus_cannon", "military_grenade_launcher", "cyborg_hands", "ritual_blade", "tactical_rifle", "sparkling_eel", "alien_sniper_rifle", "neutralizer", "bone_sniper_rifle", "prehistoric_shotgun", "shamans_bow", "poison_darts", "primal_beast", "eye_of_ra", "gym_rifle", "bone_crusher", "soda_launcher", "rocket_launcher", "royale_fighter", "royale_revolver", "royale_sniper_rifle", "royale_ashbringer", "dagger_shovels", "worker_shovel", "sniper_shovel", "gold_shovel", "jet_shovel", "shover_laser", "monster_shovel", "penilizer", "fan_revolver", "football_cannon", "shovel_axe", "cursed_pirate", "Viking", "gladiator", "heart_of_volcano", "shovel_not_a_shovel", "chainsaw_shovel", "clan_legend_shovel", "shovel_road_sign", "cactus_shovel", "toy_hammer", "igniter", "infiltrator", "warmaster", "combat_slinger", "paintball_rifle", "energy_rings_exoskeleton", "particle_accelerator", "RitualRevolvers", "magicbook_Spell_of_Bats", "deadmans_rifle", "Witchunter", "industrial_nailer", "trick_and_treat", "ghost_launcher", "poisonous_vine", "johnny_p", "witch_broom", "cyber_slicer", "ricochet_rifle", "cyber_revolver", "neon_lighting", "quadruple_death", "cops_shovel", "cyber_shovel", "rocket_hand", "cyber_laser", "scull_crossbow", "shovel_hell", "sniper_cyber_module", "cops_club", "ultimatum", "lamp_revolver", "drum_rifle", "bp_flamethrower", "hand_gatling", "steamer", "gold_digger", "bow_of_spirit", "tomahawk_shovel", "sherif_shovel", "miner_shovel", "corn_launcher", "pie_thrower", "triple_musket", "demolition_gun", "ecco_hunter", "like_throver", "photo_gun", "liquid_fire", "electric_vortex", "cursed_staff", "blinder", "peppermint_guardians", "freon_gun", "shovel_ice", "frostomat", "frosty_railgun", "winter_staff", "ice_spiker", "shovel_peppermint", "total_annihilator", "torpedo_launcher", "sawed_off_shotguns", "gauss_machine_gun", "ultra_beam", "sock_bomber", "energy_assault_rifle", "shovel_alien_ice", "shovel_ice_skate", "futuristic_minigun", "sniper_ice", "gloves_of_power", "space_redeemer", "snow_blaster", "alien_bounser", "alien_shuriken", "spruce_pistols", "christmas_spirit", "ice_lightning", "ice_generator", "icecream_pistol", "whip_with_cake", "festive_guitar", "evil_snowman", "gangerbread_homezooka", "portable_gift_factory", "saturn", "venus_n_mercury", "Asteroid", "comet_sniper_rifle", "meteor_shower", "neclaces_ice_king", "Ice_Paws", "frozen_lich_bow", "gift_stitcher", "ice_king_anger", "gifted_revolvers", "yetti_spirit", "bambo", "new_year_defender", "candy_axe", "cold_silence", "proton_freezer", "coldstarter", "cyber_machinegun", "simple_cybergun", "shock", "cyber_sniper", "simple_cyberlauncher", "simple_acid_spray", "spec_ops_backup", "pixel_cola_refresher", "warden", "instigator", "storm", "semi_auto_shotgun", "stinger_3000", "airstrike_laptop", "deadly_digital_system", "night_hunter", "spec_ops_pistol", "tactical_knife", "hand_minigun", "heavy_sniper_rifle", "armadillo", "police_zapper", "temple_guardian", "healing_carp", "moon_halberd", "magic_primary", "magic_backup", "magic_melee", "magic_special", "magic_sniper", "royale_alpenstock", "agent_valentine", "lovebirds", "Serenade", "heartbreakers", "Succubus", "postman", "harpy", "runic_hammer", "blade_rifle", "arahna_bite", "medusa", "bigb_oven", "mr_mixer", "cookie_minigun", "magic_blades", "alchemic_staff", "rune_shovel", "Ðüyclops_shovel", "system_admin", "flash_drive", "disconnector", "network_streamer", "ð░ntivirus", "big_data", "cyclops_siling", "rainbow_dispenser", "rainbow_destroyer", "mister_l", "adamant_claws", "hypersound_uzi", "double_gum", "black_hole", "space_shovel", "heroic_shovel", "protector_of_peace", "portalius_wrath", "chipping_whip", "portalium_rifle", "nuclear_rifle", "deadly_umbrella", "big_bang_revolver", "acid_shotgun", "batohawk", "combat_gautlent", "spider_sense", "werewolf", "sharp_flame", "charged_injector", "garbage_rifle", "firefighter", "huge_boy", "fireman_shovel", "fatal_melter", "dual_anger", "brutal_thinner", "", "", "", "pixelgun_old", "plastic_shovel", "balloon_shovel", "block_rifle", "block_shotgun", "block_flamethrower", "plastic_rifle", "plastic_bazooka", "plastic_carabin", "cloud_launcher", "sucker_gun", "witch_doctor", "portal_cannon", "healing_staff", "laser_ray_rifle", "clockwork_cannon", "transformed_blaster", "transformed_machinegun", "witch_cauldron", "combat_darts", "throwing_spears", "alloha_boom", "professional_bow", "artifact", "ouroboros", "keen_courier", "uncertainty_emitter", "camp_leader_rifle", "knife_and_compass", "super_loudspeaker", "raccoon_with_trumpet", "butterfly_net_shovel", "guitar_shovel", "werewolf_paws", "ice_cream_thrower", "water_juice_cannon", "pop_soda", "pyro_1116", "sparkling_hydra", "tiny_resizer", "pawn_cannon", "horse_axe", "battle_rook", "inevitability", "chess_board_shovel", "royal_shovel", "checkmate", "proud_eagle", "sly_wolf", "brave_lion", "offensive_catapult", "battle_horn", "sharp_ring", "ornate_bagpipes", "pew_pew_rifle", "pixel_stream_sword", "tube_backpack", "supershot_rifle", "hyper_mega_cannon", "", "", "", "arcade_rifle", "arcade_flamethrower", "fatality_hook", "fireball_gauntlets", "anubis", "duck_hunter", "disc_battle_station", "pixel_shovel", "holy_shotgun", "aspen_spear", "dual_hunter_crossbows", "plague_purifier", "lives_oppressor", "sword_of_silence", "gravestone_shovel", "hot_greetings", "cooking_totem", "spiritual_rifle", "storm_all_seas", "huge_anchor_shovel", "hard_corn", "chef_fork_shovel", "lancelot", "galahad", "percival_n_lamorak", "mordred", "morgana", "bediver", "neutron_pulsator", "clapper_gun", "royal_marryer", "snowqueen_wand", "heroic_epee", "ice_club", "last_squeak", "fierce_pack", "mouse_scepter", "ice_chaser", "sneaky_revolver", "coal_frightener", "enchanted_butler_shovel", "golden_bros", "gangsta_shield", "double_cashback", "luxury_beats", "sniper_dude", "gems_power", "spirit_staff", "offensive_fireworks", "sharp_fans", "river_dragon", "explosive_lemonade", "stick_gong_shovel", "fire_spirit", "thunder_storm", "water_blades", "deadly_stings", "dragon_bite", "ancient_scroll", "potato_implant", "ai_pistol", "super_drill", "meteorite_fighter", "gravitator", "predatory_bush_shovel", "zap_blaster", "pew_blaster", "boom_blaster", "psionic_spores", "poisonous_grasshopper", "shrimposaur", "desert_fighter", "egg_colorizer", "hocus_pocus", "bunny_smasher", "a_killer", "carrot_crossbow", "festive_frying_pan_shovel", "carrot_on_stick_shovel", "watchy_snipy", "spiny_shooty", "pully_blasty", "chickoboom", "battle_grainthrowers", "last_cry", "", "dragon_emitter", "fate_fist", "demon_catcher", "aboard_puncher", "deadly_tale", "ninja_shovel", "moon_shovel", "sword_soul_card", "lance_soul_card", "bow_soul_card", "vertical_grip_device", "siege_mode_glove", "one_punch_glove", "treasurer", "merchant_shovel", "shell_bubbler", "tide_bracers", "call_of_sirens", "deep_ambusher", "cthulhu_legacy", "sunken_hook_shovel", "atlantis_shovel", "mooring_anchor", "heavy_drill_rifle", "rivet_gun", "submarine_drone_station", "echo_scanner", "underwater_carbine", "", "", "", "advanced_scout_rifle", "harsh_punisher", "manual_inferno", "offensive_rocket_system", "headhunter_pistols", "thunderbolt", "spear_of_war", "aphrodite_crossbow", "winged_revolver", "ferocious_poleaxe", "hermes_rod_shovel", "hydra_shovel", "cerberus", "souls_conductor", "triple_bite", "wraith_of_fire", "earth_trembler", "primal_cold", "boar_roar", "gorgon_head", "invincible_lion", "advanced_scout_rifle_l", "harsh_punisher_l", "manual_inferno_l", "offensive_rocket_system_l", "headhunter_pistols_l", "debugger", "likes_booster", "ban_hammer", "vr_blasters", "killer_chord", "invigorating_awaker", "total_planner", "money_rain", "render_station", "gun_force", "digital_pad", "graphic_shovel", "cheater_hunter", "super_fixer", "bugs_cleaner", "code_shovel", "good_code", "ambush_crocorifle", "bubble_splasher", "disguised_rifle", "surf_daggers_shovel", "sand_shovel", "enchanting_altar", "spirit_mask", "magical_boomerang", "foam_sword", "sand_tower_pistol", "watermans_rifle", "high_pressure_rifle", "sharkado", "shower_sprinkler", "star_shard", "solar_flare", "magnetic_storm", "MonsterHunterMechBody1", "ectoplasmic_grenade_launcher", "reversed_pistol", "activity_neutralizer", "pga_mirror_shovel", "dimerian_shovel", "goo_substance_rifle", "goo_substance_pistol", "goo_substance_scythe", "pga_tv", "pga_doll", "pga_gates", "pga_living_rifle", "pga_slender_touch", "pga_screaming_saw", "atomic_splitter", "detimerian_divider", "restructurer", "anomaly_concentrator", "MonsterHunterMechBody2", "MonsterHunterMechBody3", "bloq_plasma_module", "plasma_beast", "drone_station", "arma_shovel", "police_alarm_shovel", "max_cruelty", "represser", "fear_and_espair", "rude_bully", "laser_ninja", "rebel", "mobile_outpost", "outlaw_catcher", "fair_sheriff", "minigun_cyber_module", "med_surgery_module", "supply_airdrop", "battle_falcon", "super_mega_tool", "pneumatic_needle_rifle", "summon_dagger", "melter_shovel", "pg3d_flag_shovel", "frozen_heart", "eye_of_the_storm", "frosty_fangs", "combat_candy", "ho_ho_rocket", "expllosive_caramel", "candy_revolver", "elven_killer_rifle", "assassin_daggers", "farewell_volley", "mystic_potion", "siege_crossbow", "storm_poleaxes", "prophet_staff", "hammer_of_thor", "thor_shovel", "carved_paddle_shovel", "geri_n_freki", "sleipnir", "huginn", "deceitful_cheater", "cunning_flame", "harbinger_of_ragnarok", "sun_eater", "call_of_valhalla", "winged_bow", "war_horse", "glitch_machine_gun", "ideal_rocket_launcher", "noob_rifle", "evil_rubiks_cube", "super_pixel_gun", "ultimatum_shovel", "final_sentence", "piercer", "border_eraser", "deminic_crusher", "dual_beam", "ronin", "brutal_rainbow", "tomianom", "time_scythe", "cyber_cat_lantern", "laser_cat_rifle", "bomber_cat", "lab_laser_shovel", "evidence_hunter", "patrol_officer_747", "redneck_bazooka", "mayor_trophy_revolver", "pixel_cola_cans", "city_key_shovel", "police_baton_shovel", "large_machinegun", "tactical_pistol", "mammoth", "debts_collector", "godfathers_assistant", "black_label", "plan_b", "traitor", "incinerator", "saboteur", "rock_smelter", "tunnel_riveter", "complete_grinder", "drilling_railgun", "plasmatic_digger", "drill_shovel", "portalius_shovel", "giant_flytrap_shovel", "portal_rifle", "extracting_ray_pistol", "terramorphing_stone", "aerosaur_rifle", "bone_saur_sword", "heavy_spik_saur", "ritual_rifle", "tooth_of_fate", "staff_crystals_will", "spark_horn", "adventure_swords", "flat_rifle", "secret_burger", "charles", "ink_spreader", "eraser_crossbow", "pencil_spears", "bro_steamer", "sad_magnet", "anvil_pistol", "masterly_trumpet", "blot_axe", "blot_shotgun", "blot_cannon", "adventure_shovel", "flat_shovel", "mr_shovel", "veteran_rifle", "veteran_sniper_rifle", "veteran_rocket_system", "lives_harvester", "jet_dragon", "thermal_scythe", "simple_dimple", "fx_camera", "dance_rifle", "rifle_me_online", "virtual_orchestra", "sharp_chaser", "zap_katana", "cyber_lantern", "bro_rifle", "ninja_swordpad", "hype_yo_yo", "streaming_beast", "dislike", "likes_absorber", "bad_comment", "golden_button_shovel", "pop_it_shovel", "mysterious_obelisk", "ritual_embalmer", "sacred_cat_will", "sentinel", "howl_of_the_mummy", "punishing_light", "piercing_gaze_of_ra", "eternal_suns_wrath", "fair_judge", "black_obelisk", "plaguebringer", "scarab_shrine", "disturbed_sarcophagus", "royal_cobra_spirit", "pharaon_3_breath", "sentinel_shopeish_shovel", "wand_of_summoning_shovel", "hand_mummy_shovel", "block_pyramid_shovel", "ultrasonic_rifle", "electronics_burner", "hounds_rx03", "system_scorpion", "rumble", "huge_wrench_shovel", "shovel_spear_shovel", "experimental_rifle", "jet_spear", "tactical_scorcher", "siege_minigun", "thermal_mecha_knife", "disruptive_howitzer", "anti_aircraft_module", "engineering_saw_thrower", "corpuscular_revolver", "uranium_grenade_launcher", "golden_eagles", "wayfarer", "fate", "holographic_cards", "chronos_shovel", "mutation_cannon", "additional_hand_shovel", "hungry_flower_shovel", "c4_basket", "head_of_statue", "tank_turret", "space_parasite_dreadnought", "space_parasite_fighter", "alien_parasite_mothership", "bad_clown", "disturbing_balloons", "clown_chainsaw", "irradiated_smg", "mutant_fish", "spiky_limbs", "predatory_rifle", "mutant_weapon_one", "mutant_weapon_two", "splutter_weapon_one", "splutter_weapon_two", "jumper_weapon_one", "jumper_weapon_two", "hound_weapon_one", "thorn_weapon_one", "thorn_weapon_two", "supermutant_weapon_one", "automatic_injector", "antidote_missile_launcher", "purifying_shotgun", "mutant_slayer", "mutagen_neutralizer", "antidote_dropper", "power_gauntlet", "rune_buster", "ice_wyvern_horns", "runic_sentinel", "crystal_touch", "crystal_bow", "enchanted_crystal_of_ancients", "full_moon_rifle", "fireflies_blessing", "branch_of_wisdom", "eternal_light", "mirrorer", "realities_sign_shovel", "reflected_light_shovel", "otherworld_wanderer", "dark_deer_bow", "reflected_santa_sword", "combat_fireplace", "combat_candy_machine", "gift_stealer", "tricky_glance", "end_of_fairytale", "fairy_axe", "butterfly_eater", "class_bullet_rifle", "class_knight_hammer", "class_knight_shield", "class_valk_rocket", "class_lifeline_gun", "class_sara_sniper", "class_sara_shotgun", "class_saber_disk", "class_saber_katana", "class_mex_flame", "class_viktor_grenade", "handy_darts", "spirits_whisper", "makeshift_piercer", "battle_kusarigama", "temple_claws", "summoning_totem_shovel", "cloud_standard_shovel", "vortex_core", "storm_bringer", "clouds_disperser", "field_plasma_station", "still_working_windmill", "class_lifeline_healgun", "thunder_formula", "bubblegum_01", "tnt_thrower", "ak5_56", "disguised_weapon", "intelligence_swords", "controlled_drone_system", "deadly_beamer", "tnt_holder_shovel", "aliens_shredder_shovel", "elves_energy_crystal", "tricky_electrizer", "plague_spreader", "ancestors_curse", "moon_hunter_bow", "elf_heavy_crossbow", "lightbringer", "boom_bang_shovel", "plague_flame_shovel", "ice_giant_rifle", "moonblades", "eco_rifle", "solar_lens", "blacklight_pistol", "supernova_generator", "event_horizon", "eco_shovel", "crescent_moon_shovel", "unfriendly_bat", "tamagochi_revolver", "mad_colorer", "nachos_shotgun", "skateboard_shovel", "artists_tool_shovel", "shockorizer", "crescent_power", "odm_special_gear", "sharingan_vengeance", "doubled_quirk", "grenade_quirk", "magic_moon_wand_shovel", "thunder_spear_shovel", "guardian_spirit", "ghost_epee", "the_sorting_pistol", "raven_staff", "corrupted_speelbook", "additional_biting_limb", "pocket_potion_pot_shovel", "ghost_candlestick_shovel", "transforming_rifle", "monkey_pirate", "holographic_hook_saber", "navigation_shotgun", "three_barrels_cannon", "ships_drowner", "cosmo_underwater_mine_shovel", "living_specimen_shovel", "deadly_shark", "wardens_trident", "nets_thrower", "tick_tock_pistol", "heavy_cone_minigun", "starfall", "dreams_warden", "snowstorm_fury", "spirits_overseer", "s_q_dominion", "x_mas_vibes_setter", "fatal_decorator", "x_mas_spirits_defender", "nature_guards_shovel", "starfall_shovel", "harsh_dragon", "armor_piercing_sniper_rifle", "leaders_butterfly", "leaders_bestfriend", "reckoning_day_sniper_rifle", "reckoning_day_pistols", "flaming_reckoning_day", "festive_eliminator", "spirit_exorcist", "wealth_spreader", "ultimate_worship", "ritual_scissors", "dark_ritual", "light_devourer", "bloody_terror_axe", "sacrificial_altar", "hunting_signs", "monster_hand", "locator", "terror_spreader", "spring_snatcher", "sticky_honey_dipper", "chefs_bounty", "cloying_eliminator", "take_your_ice_cream", "pasta_grater", "pasta_sniper_rifle", "pasta_maker", "pg_menu", "space_cycler", "anniversary_alien_blaster", "anniversary_auto_peace", "anniversary_anti_champion", "anniversary_big_buddy", "pixel_rotator", "armored_cuber_power", "cuber_railgun", "secret_pg_archives", "block_eye", "honored_golden_friend", "classic_shovel", "usher", "special_throwing_knives", "springy_shotgun", "clockwork_guardian", "dark_foreteller", "deadly_tent", "playing_pistols", "card_sharper", "scary_bunny", "accurate_bubbler", "soap_hammer", "dangerous_miner", "path_lighter", "heavy_anchor", "deadly_tide", "abyssal_altar", "underwater_whip", "underwater_piercer", "underwater_overseer", "cyber_sai", "intelligent_cyber_bow", "deathbringer", "total_dominator_2", "evasive_dominator_4", "virus_spreader", "errors_generator", "revenger", "exchanger", "rebellion_spray_paints", "rosies_diary", "sharp_butterfly_rifle", "heart_maze", "stationery_friend", "paper_assist", "friendliest_pistol", "innocent_sniper_rifle", "kitten_kutie", "neon_tommy_gun", "neon_colt_1911", "heavy_neon_gun", "danger_posy", "spiky_mortar", "heavy_evidence", "useful_suitcase", "accurate_investigator", "", "", "", "cash_gun", "rudolf_the_deer", "sooty_sniper_rifle", "chris_letters_shredder", "ninja_ice_axe", "cold_shinobi", "ice_ball_generator", "deadly_icing", "drag_sc", "dragoneer", "noble_porce", "dragon_x", "flaming_fan", "flaming_fury", "kn_arbalet", "scepter_and_power", "invig_drink", "bards_song", "gears_of_death", "kill_mech", "assas_assis", "souls_cycler", "arc_souls_dev", "pois_pier", "v_cleaner_sl", "rust_revol", "wooden_rifle", "forester", "forest_prot", "harm_sint", "high_vol_prop", "drag_wrath", "drag_heart", "glass_pain_prot", "hypno_hunter", "hypno_shackles", "hypno_hursuer", "cosmis_geode", "", "portal_ess", "party_sniper_rifle", "win_las_beam", "cosmic_wayfarer", "Itrgal_treasurer", "game_addc_gun", "00s_gadgets_rifle", "explsv_soap", "bld_mrcnr", "dead_nb", "pixeletta_guns", "devil_cry_sword", "city17_crossbow", "shovel_unbreakable", "obsidian_darts", "aztec_death_whistle", "neo_macuahuitl", "coatl_whip", "mictlanbound", "pillar_of_mictlan", "spicy_crab_roll", "sledge_hammer", "teponaztli", "scorching_split", "coatl_whip", "mictlanbound", "pillar_of_mictlan", "spicy_crab_roll", "beetles_wand", " dandelion_artillery", "punching_mushroom", "red_list", "mothing_devastator", "mothfire_catalyst", "moth_queens_gaze", "robbie_the_protector_shovel", "petal_pyro" };
    const char* BanList[1] = { "fps_destroyer" };
    const char* WeaponsLoadout[6] = { "ultimatum", "bld_mrcnr", "double_cashback", "gift_stealer", "harsh_punisher", "pixel_cola_refresher" };
    const char* ArmorLoadout[5] = { "developer_armor", "league6_hat_tiara", "mask_halloween_up2", "cape_Custom", "BerserkBoots_Up2" };
    const char* GadgetLoadout[2] = { "gadget_cyber_bees", "gadget_denied" };

	const char* GadgetsList[48] = { "gadget_armor_regeneration", "gadget_astral", "gadget_bionic_shield", "gadget_black_label", "gadget_Blizzard_generator", "gadget_christmastreeturret", "gadget_combat_spinner", "gadget_cyber_bees", "gadget_cybersamurai", "gadget_demon_stone", "gadget_denied", "gadget_disabler", "gadget_dragonwhistle", "gadget_fakebonus", "gadget_firecrackers", "gadget_firemushroom", "gadget_firework", "gadget_fraggrenade", "gadget_guardian", "gadget_hologram_projector", "gadget_jetpack", "gadget_leaderdrum", "gadget_mech", "gadget_medkit", "gadget_mh_mech1", "gadget_mh_mech2", "gadget_mh_mech3", "gadget_mine", "gadget_molotov", "gadget_ninjashurickens", "gadget_nucleargrenade", "gadget_nutcracker", "gadget_pandorabox", "gadget_petbooster", "gadget_phoenix_blood", "gadget_pocket_harpoon", "gadget_reflector", "gadget_rocket_mech", "gadget_shield", "gadget_singularity", "gadget_snowman", "gadget_stealth", "gadget_sticky_turret", "gadget_stickycandy", "gadget_super_magnet", "gadget_timewatch", "gadget_turret", "gadget_x-ray_glasses" };
	int Gadgets = 0;

	const char* HatList[30] = { "league1_hat_hitman", "league2_hat_cowboyhat", "league3_hat_afro", "league4_hat_mushroom", "league5_hat_brain", "league6_hat_tiara", "hat_Adamant_3", "hat_Headphones", "hat_black_dragon", "hat_chest", "hat_KingsCrown", "hat_stardust", "hat_Samurai", "hat_DiamondHelmet", "hat_SeriousManHat", "hat_cyber_santa", "hat_cyber_santa_Up1", "hat_cyber_santa_Up2", "hat_exoskeleton_pilot_avatar", "hat_exoskeleton_pilot_avatar_up1", "hat_exoskeleton_pilot_avatar_up2", "hat_halloween", "hat_halloween_up1", "hat_halloween_up2", "hat_piligrim", "hat_piligrim_up1", "hat_piligrim_up2", "hat_high_end_earphones", "hat_magic_gift", "hat_space_delivery"};
	const char* ArmorList[29] = { "Armor_Adamant_Const_2", "Armor_Almaz_3", "Armor_Army_1", "Armor_Army_3", "armor_black_dragon", "armor_clan_golden", "armor_clan_steel", "armor_clan_wooden", "armor_crystal_clan", "armor_dope_windcheater", "Armor_Halloween", "armor_inflatable", "Armor_Royal_3", "Armor_Rubin_3", "armor_stardust", "Armor_Steel_3", "armor_ultimate_defense", "cyber_santa_armor", "developer_armor", "exoskeleton_pilot_avatar_armor", "heavy_champion_armor", "pilgrim_armor", "starter_pack_armor", "armor_space_delivery", "armor_superhero", "armor_cash", "armor_cash_fix", "armor_magic_gift", "armor_natural" };
	const char* BootList[38] = { "boots_gray", "StormTrooperBoots_Up1", "StormTrooperBoots_Up2", "boots_red", "HitmanBoots_Up1", "HitmanBoots_Up2", "boots_black", "BerserkBoots_Up1", "BerserkBoots_Up2", "EngineerBoots", "EngineerBoots_Up1", "EngineerBoots_Up2", "boots_blue", "SniperBoots_Up1", "SniperBoots_Up2", "boots_green", "DemolitionBoots_Up1", "DemolitionBoots_Up2", "boots_tabi", "boots_cyber_santa", "boots_cyber_santa_Up1", "boots_cyber_santa_Up2", "boots_exoskeleton_pilot_avatar", "boots_exoskeleton_pilot_avatar_up1", "boots_exoskeleton_pilot_avatar_up2", "boots_black_dragon", "boots_halloween", "boots_halloween_up1", "boots_halloween_up2", "boots_roller_skates", "boots_stardust", "boots_ultimate_defense", "boots_piligrim", "boots_piligrim_up1", "boots_piligrim_up2", "boots_magic_gift", "boots_natural", "boots_space_delivery" };
	const char* MaskList[40] = { "mask_trooper", "mask_trooper_up1", "mask_trooper_up2", "mask_hitman_1", "mask_hitman_1_up1", "mask_hitman_1_up2", "mask_berserk", "mask_berserk_up1", "mask_berserk_up2", "mask_engineer", "mask_engineer_up1", "mask_engineer_up2", "mask_sniper", "mask_sniper_up1", "mask_sniper_up2", "mask_demolition", "mask_demolition_up1", "mask_demolition_up2", "hat_ManiacMask", "mask_cyber_santa", "mask_cyber_santa_Up1", "mask_cyber_santa_Up2", "mask_exoskeleton_pilot_avatar", "mask_exoskeleton_pilot_avatar_up1", "mask_exoskeleton_pilot_avatar_up2", "mask_halloween", "mask_halloween_up1", "mask_halloween_up2", "mask_black_dragon", "mask_doctor_plague", "mask_medical_mask", "mask_turkey_piligrim", "mask_turkey_piligrim_up1", "boots_piligrim_up1", "mask_turkey_piligrim_up2", "mask_ultimate_defense", "mask_anime_glasses", "mask_smart_bullet_bazooka", "mask_stop_posting_hepi", "mask_natural" };
	const char* CapeList[32] = { "cape_Custom", "cape_EliteCrafter", "StormTrooperCape_Up1", "StormTrooperCape_Up2", "cape_Archimage", "HitmanCape_Up1", "HitmanCape_Up2", "cape_BloodyDemon", "BerserkCape_Up1", "BerserkCape_Up2", "cape_Engineer", "cape_Engineer_Up1", "cape_Engineer_Up2", "cape_SkeletonLord", "SniperCape_Up1", "SniperCape_Up2", "cape_cloak_of_night", "cape_ultimate_defense", "cape_vaneuvering_module", "cape_RoyalKnight", "DemolitionCape_Up1", "DemolitionCape_Up2", "cape_boss", "cape_boun_space", "cape_fun_fair_cape", "cape_gifts", "cape_loyalty", "cape_of_intelligence", "cape_of_loneliness", "cape_screen", "cape_magic_gift", "cape_pg_hero_cape" };

	const char* VeteranList[5] = { "hat_veteran", "armor_veteran", "cape_veteran", "boots_veteran", "mask_veteran" };

	int Polymorpher = 0;
	const char* PolymorpherType[5] = { "Sheep", "Beetle", "Mutant", "Cube", "AncKnow" };

    const char* AvatarList[472] = {
        "avarar_krampus_elf",
        "avatar_3catspammer",
        "avatar_70_corruption",
        "avatar_90_Corruption",
        "avatar_programmer",
        "avatar_aborigine",
        "avatar_absolute_champion",
        "avatar_absolute_champion_ice",
        "avatar_advanced_soldier",
        "avatar_adventure_dog",
        "avatar_agent_p",
        "avatar_agent_r",
        "avatar_agent_s",
        "avatar_agent_u",
        "avatar_agent_x",
        "avatar_agressivebot",
        "avatar_alchemist",
        "avatar_alien_santa",
        "avatar_aliens_executioner",
        "avatar_alpha_squad",
        "avatar_amazing_robert_cat",
        "avatar_amazon",
        "avatar_angler",
        "avatar_animator",
        "avatar_anniversary_netrunner",
        "avatar_anubis",
        "avatar_aphrodite",
        "avatar_arctic_souls",
        "avatar_ares",
        "avatar_arma_colonel",
        "avatar_armed_assistant",
        "avatar_assistant_hot_dog",
        "avatar_author",
        "avatar_awakened_mummy",
        "avatar_bad_guy",
        "avatar_bad_guy_3",
        "avatar_bad_santa",
        "avatar_balloonman",
        "avatar_bandits_leader",
        "avatar_barbarian",
        "avatar_benny",
        "avatar_BigB",
        "avatar_bizarre_macho",
        "avatar_black_dragon",
        "avatar_blockcity_detective",
        "avatar_blockman",
        "avatar_blogger",
        "avatar_blogger_girl",
        "avatar_bloq_directors",
        "avatar_blot",
        "avatar_blue_soldier",
        "avatar_bobcorn",
        "avatar_boy_with_duck",
        "avatar_brave_fireman",
        "avatar_brave_knight",
        "avatar_brave_priest",
        "avatar_brave_slayer",
        "avatar_bravo_squad",
        "avatar_breadboy",
        "avatar_bri_of_life",
        "avatar_bronze_hero",
        "avatar_brutal_deer",
        "avatar_bubble_queen",
        "avatar_bug_catcher",
        "avatar_camp_counselor",
        "avatar_campaign_girl",
        "avatar_captain_pixelgun",
        "avatar_caramel",
        "avatar_carrot",
        "avatar_cat_admirer",
        "avatar_cat_in_boots",
        "avatar_cat_maiden",
        "avatar_catcher_teen",
        "avatar_chicken_667",
        "avatar_chinatown_band_leader",
        "avatar_chinatown_fighter",
        "avatar_chinatown_thug",
        "avatar_chosen_crystal",
        "avatar_chronos",
        "avatar_chubby_viking",
        "avatar_city_fighter",
        "avatar_clan_legend",
        "avatar_classic_zombie",
        "avatar_clockwork_catherine",
        "avatar_colonist",
        "avatar_colonist_2",
        "avatar_combat_christmas_tree",
        "avatar_community_manager",
        "avatar_confident_researcher",
        "avatar_cosmo_conqueror",
        "avatar_cosmus",
        "avatar_crab",
        "avatar_crampus_cookie",
        "avatar_crystal_golem",
        "avatar_cube_the_greatest",
        "avatar_curious_detective",
        "avatar_cursed_pharaoh",
        "avatar_cyber_citizen",
        "avatar_cyber_girl",
        "avatar_cyber_hare",
        "avatar_cybercop",
        "avatar_cyborg_boar",
        "avatar_cyborg_rhino",
        "avatar_cyclop",
        "avatar_daisy",
        "avatar_dance_queen",
        "avatar_dark_assassin",
        "avatar_dark_mage_mimic",
        "avatar_dark_wood_spirit",
        "avatar_daugter",
        "avatar_dazzling_moth",
        "avatar_dazzling_sage",
        "avatar_deep_monster",
        "avatar_deft_shinobi",
        "avatar_demonic_illusionist",
        "avatar_depths_commander",
        "avatar_depths_queen",
        "avatar_desperate_lab_assistant",
        "avatar_digital_gambler",
        "avatar_digital_hero",
        "avatar_diligent_novice",
        "avatar_dis_sur_pm",
        "avatar_divided_santa",
        "avatar_dolphin_willy",
        "avatar_don",
        "avatar_donny_dark",
        "avatar_dons_hand",
        "avatar_dr_pio",
        "avatar_dr_plague",
        "avatar_drag_reb",
        "avatar_dragon_child",
        "avatar_dragoon",
        "avatar_dreams_queen",
        "avatar_drilling_drone",
        "avatar_druid",
        "avatar_dvr_v_05_s",
        "avatar_dwarves_king",
        "avatar_eared_spec_forces",
        "avatar_earth",
        "avatar_eddy_mesmer",
        "avatar_edelonne_the_undead",
        "avatar_eirik_oakbreaker",
        "avatar_elementals_challenger",
        "avatar_elite_marine_ops",
        "avatar_elite_police_drone",
        "avatar_elven_prince",
        "avatar_enchanted_nutcracker",
        "avatar_entertainments_seller",
        "avatar_expert_scout",
        "avatar_fall_tree",
        "avatar_far_future_loner",
        "avatar_fearless_nun",
        "avatar_femme_fatale",
        "avatar_fenrir",
        "avatar_ff_knight",
        "avatar_final_boss",
        "avatar_firefly",
        "avatar_flat_boy",
        "avatar_flory",
        "avatar_fluff",
        "avatar_flying_dutchman",
        "avatar_forest_guardian",
        "avatar_forgotten_astronaut",
        "avatar_fortune_speaker",
        "avatar_friendlybot",
        "avatar_froggy",
        "avatar_front_man",
        "avatar_frozen",
        "avatar_future_ninja",
        "avatar_fx_master",
        "avatar_game_designer",
        "avatar_gamer_samurai",
        "avatar_gang_leader",
        "avatar_general_bullet",
        "avatar_general_green",
        "avatar_ghost_designer",
        "avatar_ghost_in_shell",
        "avatar_giga_captain",
        "avatar_gingerbread",
        "avatar_gIrl_no3_type_d",
        "avatar_glitch_player",
        "avatar_goblin_rogue",
        "avatar_golden_hero",
        "avatar_golden_ra",
        "avatar_goliath",
        "avatar_good_ol_bomber",
        "avatar_good_yeti",
        "avatar_graph_blockula",
        "avatar_greensoldier",
        "avatar_grumbler",
        "avatar_guardian",
        "avatar_gum_beast",
        "avatar_guns_bunny",
        "avatar_gunslinger",
        "avatar_halfmetal_mechanist",
        "avatar_hater",
        "avatar_head_of_academy",
        "avatar_heavy_dive_suit",
        "avatar_heavy_siege_robot",
        "avatar_heavy_stormtrooper",
        "avatar_helga_the_breaker",
        "avatar_helicopter_pilot",
        "avatar_hercules",
        "avatar_hermes",
        "avatar_hooligan_girl",
        "avatar_human_rebel",
        "avatar_humpty_dumpty",
        "avatar_ice_dragon_adept",
        "avatar_ice_dragon_shaman",
        "avatar_ice_heart_guard",
        "avatar_ice_iream_creature",
        "avatar_ice_lich_king",
        "avatar_ice_ninja",
        "avatar_ice_titan",
        "avatar_igor",
        "avatar_impositor_black",
        "avatar_impositor_blue",
        "avatar_impositor_cyan",
        "avatar_impositor_green",
        "avatar_impositor_orange",
        "avatar_impositor_pink",
        "avatar_impositor_red",
        "avatar_impositor_violet",
        "avatar_impositor_white",
        "avatar_impositor_yellow",
        "avatar_indian_boy",
        "avatar_indian_girl",
        "avatar_infected_scientist",
        "avatar_infection_fighter",
        "avatar_inquisitive_diver",
        "avatar_inquisitive_scientists",
        "avatar_insidious_hades",
        "avatar_iron_warrior",
        "avatar_irradiated_pixelman",
        "avatar_jason_drill",
        "avatar_joystick",
        "avatar_junior_cult_member",
        "avatar_kartoszewski",
        "avatar_katty_pop",
        "avatar_khepri",
        "avatar_king",
        "avatar_king_of_bros",
        "avatar_kitty",
        "avatar_knight",
        "avatar_knitteddoll",
        "avatar_knitteddoll_newyear",
        "avatar_kraken_cult_knight",
        "avatar_krampus",
        "avatar_krampus_elf",
        "avatar_krampus_elf_ice",
        "avatar_lab_prototype",
        "avatar_lava_titan",
        "avatar_lee_gun",
        "avatar_legendary_captain",
        "avatar_legionary",
        "avatar_level_37_guide",
        "avatar_light_paladin",
        "avatar_lighthouse_keeper",
        "avatar_living_armor",
        "avatar_log",
        "avatar_loki",
        "avatar_lone_roamer",
        "avatar_lost_rosie",
        "avatar_lvl_65_hero",
        "avatar_mad",
        "avatar_madcap_girlie",
        "avatar_mafia_head",
        "avatar_magical_rabbit",
        "avatar_main_foll",
        "avatar_maniac_artist",
        "avatar_mayor",
        "avatar_mech_pilot_exo1",
        "avatar_mech_pilot_exo2",
        "avatar_mecha_raccoon",
        "avatar_med_paramedic",
        "avatar_mermaid_princess",
        "avatar_mighty_shaman",
        "avatar_mikhail_steel",
        "avatar_minotaurus",
        "avatar_miscreant_chef",
        "avatar_modern_ninja",
        "avatar_monster_hunter",
        "avatar_moon",
        "avatar_moon_elf",
        "avatar_moon_princess",
        "avatar_mouse_king",
        "avatar_mr_bite",
        "avatar_mr_bucket",
        "avatar_mr_monke",
        "avatar_mr_streamer",
        "avatar_mr_ultimatum",
        "avatar_ms_doc",
        "avatar_mutated_monster",
        "avatar_mysterious_lady",
        "avatar_mysterious_warden",
        "avatar_mystic_merchant",
        "avatar_mystical_fairy",
        "avatar_nature_spirit",
        "avatar_navy_tactical_suit",
        "avatar_neon",
        "avatar_neptune",
        "avatar_netrunner",
        "avatar_nimble_viking",
        "avatar_ninja_fox",
        "avatar_ninja_robot",
        "avatar_noob",
        "avatar_novice",
        "avatar_oak_bot",
        "avatar_obscurant",
        "avatar_odin",
        "avatar_oldrobot",
        "avatar_orange",
        "avatar_orc",
        "avatar_party_bot",
        "avatar_pawn",
        "avatar_perky_bard",
        "avatar_pg_burger",
        "avatar_pga_goo",
        "avatar_phoenix_warrior",
        "avatar_pi_xel",
        "avatar_pilgrim_boy",
        "avatar_pilgrim_girl",
        "avatar_pirqates_queen",
        "avatar_pixel_cola_mascot",
        "avatar_pixel_man",
        "avatar_player_1",
        "avatar_player_2",
        "avatar_polar_archaeologist",
        "avatar_policeman",
        "avatar_port_fin_form",
        "avatar_portalius",
        "avatar_potions_master",
        "avatar_professor_stone",
        "avatar_project_manager",
        "avatar_prospector",
        "avatar_pyramid_builder",
        "avatar_queen",
        "avatar_quirky_boy",
        "avatar_radioactive_girl",
        "avatar_raptor",
        "avatar_red_pan_dah",
        "avatar_red_skull",
        "avatar_red_skull_ice",
        "avatar_red_soldier",
        "avatar_redneck",
        "avatar_redskin",
        "avatar_rescuer",
        "avatar_revived",
        "avatar_richman",
        "avatar_robb_e",
        "avatar_robo_elf",
        "avatar_robotic",
        "avatar_robotron",
        "avatar_rock_titan",
        "avatar_rocket_jumper",
        "avatar_rocksy",
        "avatar_rook",
        "avatar_royal_confidant",
        "avatar_rubus",
        "avatar_ruin_demon",
        "avatar_runaway_statue",
        "avatar_sad_sally",
        "avatar_same_prince",
        "avatar_santa_brawler",
        "avatar_santa_helper",
        "avatar_sara_zoom",
        "avatar_scarab_priest",
        "avatar_school_ghost",
        "avatar_scout",
        "avatar_scuba_diving_scout",
        "avatar_seas_overlord",
        "avatar_secret_character",
        "avatar_secret_mech_prototype",
        "avatar_security_circle",
        "avatar_security_square",
        "avatar_security_triangle",
        "avatar_sharko",
        "avatar_sheriff",
        "avatar_shining_moon",
        "avatar_shiny",
        "avatar_ships_robot",
        "avatar_silent_survivor",
        "avatar_silver_hero",
        "avatar_skeleton_pirate",
        "avatar_skeptic_boy",
        "avatar_ski_girl",
        "avatar_small_brawler",
        "avatar_snow_queen",
        "avatar_sorcerers_apprentice",
        "avatar_soundman",
        "avatar_space_bounded_captain",
        "avatar_spaghetti_monster",
        "avatar_spark",
        "avatar_spec_ops",
        "avatar_spec_ops_boss",
        "avatar_spec_ops_boy",
        "avatar_spec_ops_girl",
        "avatar_spec_ops_tactical_mech",
        "avatar_spiky",
        "avatar_squad_captain",
        "avatar_squid_001",
        "avatar_squid_002",
        "avatar_squid_003",
        "avatar_squid_004",
        "avatar_squid_005",
        "avatar_starlighter",
        "avatar_steel_man",
        "avatar_storms_overlord",
        "avatar_strange_creature",
        "avatar_street_king",
        "avatar_strongman",
        "avatar_summer_spirit",
        "avatar_summoned_snowman",
        "avatar_sun",
        "avatar_sun_elf",
        "avatar_super_bowl_player",
        "avatar_super_mutant",
        "avatar_super_portalius",
        "avatar_super_pro",
        "avatar_super_star_girl",
        "avatar_supreme_lich",
        "avatar_supreme_prophet",
        "avatar_supreme_space_parasite",
        "avatar_the_ancient_god",
        "avatar_the_boss",
        "avatar_the_bug",
        "avatar_the_chosen_one",
        "avatar_the_creator",
        "avatar_the_empress",
        "avatar_the_everything",
        "avatar_the_mirror",
        "avatar_the_shadow",
        "avatar_the_sun",
        "avatar_thegreatestai",
        "avatar_thor",
        "avatar_time_keeper",
        "avatar_treasure_raider",
        "avatar_treasure_warden",
        "avatar_tree_spirit",
        "avatar_triceratops",
        "avatar_troll_warchief",
        "avatar_trophy_fighter",
        "avatar_trophy_master",
        "avatar_trophy_novice",
        "avatar_turkey_guy",
        "avatar_twinkle",
        "avatar_undercover_agent",
        "avatar_unknown",
        "avatar_up_future_ninja",
        "avatar_vacation_girl",
        "avatar_valiant_savior",
        "avatar_valkyrie",
        "avatar_vampire_hunter",
        "avatar_viktor_grom",
        "avatar_virtual_blogger",
        "avatar_water_warrior",
        "avatar_weak_willed_puppet",
        "avatar_werewolf",
        "avatar_wildwood_creature",
        "avatar_winter_boy",
        "avatar_winter_girl",
        "avatar_wise_shogun",
        "avatar_wooden",
        "avatar_yakuza",
        "avatar_yellow_slicker",
        "avatar_yellowsoldier",
        "avatar_zeus",
        "avatar_zimzerla",
        "avatar_zombie_clown",
        "avatar_zombie_dude",
        "avatar_zombified_alien",
        "avatar_еmperor_son"
    };

    const char* ShovelList[103] = {
    "additional_hand_shovel",
    "adventure_shovel",
    "aliens_shredder_shovel",
    "arma_shovel",
    "artists_tool_shovel",
    "atlantis_shovel",
    "balloon_shovel",
    "block_pyramid_shovel",
    "boom_bang_shovel",
    "butterfly_net_shovel",
    "cactus_shovel",
    "carrot_on_stick_shovel",
    "carved_paddle_shovel",
    "chainsaw_shovel",
    "chef_fork_shovel",
    "chess_board_shovel",
    "chronos_shovel",
    "city_key_shovel",
    "clan_legend_shovel",
    "classic_shovel",
    "cloud_standard_shovel",
    "code_shovel",
    "cops_shovel",
    "cosmo_underwater_mine_shovel",
    "crescent_moon_shovel",
    "cyber_shovel",
    "cyclops_shovel",
    "dagger_shovels",
    "dimerian_shovel",
    "drill_shovel",
    "eco_shovel",
    "enchanted_butler_shovel",
    "festive_frying_pan_shovel",
    "fireman_shovel",
    "flat_shovel",
    "ghost_candlestick_shovel",
    "giant_flytrap_shovel",
    "gold_shovel",
    "golden_button_shovel",
    "graphic_shovel",
    "gravestone_shovel",
    "guitar_shovel",
    "hand_mummy_shovel",
    "hermes_rod_shovel",
    "heroic_shovel",
    "huge_anchor_shovel",
    "huge_wrench_shovel",
    "hungry_flower_shovel",
    "hydra_shovel",
    "jet_shovel",
    "lab_laser_shovel",
    "living_specimen_shovel",
    "magic_moon_wand_shovel",
    "melter_shovel",
    "merchant_shovel",
    "miner_shovel",
    "monster_shovel",
    "moon_shovel",
    "mr_shovel",
    "nature_guards_shovel",
    "ninja_shovel",
    "pg3d_flag_shovel",
    "pga_mirror_shovel",
    "pixel_shovel",
    "plague_flame_shovel",
    "plastic_shovel",
    "pocket_potion_pot_shovel",
    "police_alarm_shovel",
    "police_baton_shovel",
    "pop_it_shovel",
    "portalius_shovel",
    "predatory_bush_shovel",
    "realities_sign_shovel",
    "reflected_light_shovel",
    "royal_shovel",
    "rune_shovel",
    "sand_shovel",
    "sentinel_shopeish_shovel",
    "sherif_shovel",
    "shovel_alien_ice",
    "shovel_axe",
    "shovel_hell",
    "shovel_ice",
    "shovel_ice_skate",
    "shovel_not_a_shovel",
    "shovel_peppermint",
    "shovel_road_sign",
    "shovel_spear_shovel",
    "skateboard_shovel",
    "sniper_shovel",
    "space_shovel",
    "starfall_shovel",
    "stick_gong_shovel",
    "summoning_totem_shovel",
    "sunken_hook_shovel",
    "surf_daggers_shovel",
    "thor_shovel",
    "thunder_spear_shovel",
    "tnt_holder_shovel",
    "tomahawk_shovel",
    "ultimatum_shovel",
    "wand_of_summoning_shovel",
    "worker_shovel"
    };

    const char* GliderList[123] = {
    "glider_additional_deck",
    "glider_aero_suit",
    "glider_air_raider",
    "glider_air_surfboard",
    "glider_airborne_basket",
    "glider_ancient_dragon_spirit",
    "glider_ancient_tome",
    "glider_antidote_spray",
    "glider_armored_flyer",
    "glider_band_leaders",
    "glider_basic",
    "glider_bday_party",
    "glider_beerocopter",
    "glider_big_bomb",
    "glider_block",
    "glider_blogger",
    "glider_blood_butterfly",
    "glider_bloq_jetpack",
    "glider_boat_of_ra",
    "glider_bubble",
    "glider_butterfly_of_light",
    "glider_cartoon_plane",
    "glider_chainsaw",
    "glider_comfortable_magic_broom",
    "glider_copter",
    "glider_cristmas_keeper",
    "glider_cybercop",
    "glider_d-day_pod",
    "glider_death_herald",
    "glider_dense_shadows",
    "glider_dragon",
    "glider_dragon_form",
    "glider_dragon_spirit",
    "glider_drill",
    "glider_drone",
    "glider_elven_cloak",
    "glider_executers_high_end",
    "glider_extraterrestrial_hoverboard",
    "glider_festive_ski",
    "glider_flutter_pony",
    "glider_flying_manta",
    "glider_futuristic",
    "glider_garbage",
    "glider_gas_o_copter",
    "glider_giant_bat",
    "glider_giant_bubble",
    "glider_giant_scarab",
    "glider_good_ol_plane",
    "glider_handmade",
    "glider_hawk",
    "glider_high_intelligent",
    "glider_ice_cream",
    "glider_ice_wings",
    "glider_icewing_dragon",
    "glider_inflatable_banana",
    "glider_judge_rocket",
    "glider_kite",
    "glider_kleptomaniacs_boat",
    "glider_leader",
    "glider_loaded_koi",
    "glider_mad_dyer",
    "glider_magic_broom",
    "glider_magic_horse",
    "glider_magic_wings",
    "glider_magical_hat",
    "glider_mattress",
    "glider_mechanical_wings",
    "glider_membrawinger",
    "glider_merchant",
    "glider_merry_go_round_horse",
    "glider_military",
    "glider_money_case",
    "glider_mutated_wings",
    "glider_neon",
    "glider_neon_bike",
    "glider_netrunner",
    "glider_pegasus",
    "glider_pew_pew_spaceship",
    "glider_phoenix",
    "glider_phoenix_wings",
    "glider_pocket_bat",
    "glider_poison_bubble",
    "glider_police_cage",
    "glider_poncho",
    "glider_popit",
    "glider_portalius",
    "glider_powerful_entity",
    "glider_pro_hoverboard",
    "glider_queens_flower",
    "glider_ramen_noodle",
    "glider_rapid_hoverbike",
    "glider_raven_form",
    "glider_reality_border",
    "glider_reb_mono",
    "glider_reponosaurus",
    "glider_satellite",
    "glider_shooting_stars",
    "glider_simple_jetpack",
    "glider_skyfly_3000",
    "glider_soaring_sandals",
    "glider_soundman",
    "glider_space_bounded",
    "glider_space_mechas_carrier",
    "glider_starlet",
    "glider_steam",
    "glider_sunstrider",
    "glider_super_power",
    "glider_tamed_zombolisk",
    "glider_tank_for_mutant",
    "glider_terra_board",
    "glider_time_haste",
    "glider_titans_slayers",
    "glider_toy_horse",
    "glider_tranquility_stone",
    "glider_transport_helicopter",
    "glider_ufo",
    "glider_vacation_baggage",
    "glider_valkyrie_wings",
    "glider_vecha_glider",
    "glider_vulture",
    "glider_yellow_duck",
    "Hang_glider",
    "wooden_glider"
    };

    const char* TrailList[137] = {
        "aaaaa_trail",
        "air_trail",
        "ancient_ice_trail",
        "awak_blos_trail",
        "balloons_trail",
        "barbed_wire_trail",
        "bats_trail",
        "beautiful_shells_trail",
        "berserker_trail",
        "black_rabbit_gangs_trail",
        "block_trail",
        "bloq_commercial_trail",
        "bombs_trail",
        "bugs_trail",
        "bullet_trail",
        "buttons_trail",
        "candies_trail",
        "carpet_plane",
        "carrots_trail",
        "cartoon_clouds_trail",
        "cartoon_start_trail",
        "checkerboard_trail",
        "chess_trail",
        "circus_lights_trail",
        "clan_trail",
        "colorful_smoke_trail",
        "comet_trail",
        "confetti_trail",
        "crescent_princess_trail",
        "deadly_plague_trail",
        "decorated_feathers_trail",
        "digits_trail",
        "dislikes_trail",
        "disputes_trail",
        "dragon_form_trail",
        "drill_trail",
        "dust_trail",
        "earth_atmosphere_trail",
        "energetic_trail",
        "executed_aliens_storage_trail",
        "extinguiser_trail",
        "fast_furious_trail",
        "festive_glider",
        "fiery_trail",
        "firecrackers_trail",
        "firework_trail",
        "flashlights_trail",
        "glitch_trail_trail",
        "goo_trail",
        "graphic_trail",
        "gravilith_trail",
        "gum_trail",
        "hail_of_arrows_trail",
        "hare_firefly_trail",
        "helicopter_military",
        "hologram_raccoon_trail",
        "holy_light_trail",
        "ice_trail",
        "inquisitive_bubbles_trail",
        "jubilee_trail",
        "lava_lamp_trail",
        "leaf_trail",
        "lemonade_bubbles_trail",
        "likes_trail",
        "love_trail",
        "mafia_trail",
        "magic_trail",
        "marshmallow_trail",
        "menacing_trail",
        "merchant_hood",
        "merchant_trail",
        "mini_helicopters_trail",
        "mirrored_night_trail",
        "money_trail",
        "moonlight_trail",
        "mutated_dna_trail",
        "mystery_notes_trail",
        "mystic_snakes_trail",
        "neon_trail",
        "neptune_ices_trail",
        "new_ear_trail",
        "old_scrolls_trail",
        "ominous_trail",
        "ovum_trail",
        "pg_is_love_trail",
        "pixel_cola_trail",
        "plague_trail",
        "poisonous_trail",
        "poisonous_vines_trail",
        "police_alert_hologram_trail",
        "popcorn_trail",
        "power_up_trail",
        "quick_feathers_trail",
        "rainbow_trail",
        "roast_turkey",
        "rocket_pursuit_trail",
        "rocks_trail",
        "rune_trail_trail",
        "sakura_flowers_trail",
        "scout_trail",
        "secret_documents_trail",
        "shadow_trail",
        "shamanic_symbols_trail",
        "shiny_mutagen_trail",
        "signal_trail",
        "sinister_tentacles_trail",
        "snow_trail",
        "snowballs_trail",
        "snowflakes_trail",
        "sos_trail",
        "sparkling_stardust_trail",
        "speed_up_trail",
        "spheres_of_power_trail",
        "star_trail",
        "stardust_trail",
        "starfall_trail",
        "storm_trail",
        "storm_vortex_trail",
        "strange_potion_trail",
        "summer_flowers_trail",
        "sun_rays_trail",
        "sunny_trail",
        "super_antidote_trail",
        "superhero_cape",
        "tactical_glider",
        "tamagochi_trail",
        "thunderstrike_trail",
        "time_running_trail",
        "ultimatum_trail_trail",
        "vampire_trail",
        "virtual_trail",
        "virus_trail",
        "volcano_trail",
        "water_trail",
        "wedding_rings_trail",
        "zeus_wrath_trail",
        "сurvature_of_space_trail"
    };

    const char* VehicleNames[67] = {
            "royale_amphibian",
            "royale_atv",
            "royale_car_all_terrain_tank",
            "royale_car_all_terrain_vehicle",
            "royale_car_antimutant_bus",
            "royale_car_armored_stryker",
            "royale_car_backrooms_traveller",
            "royale_car_basic",
            "royale_car_battle_transport",
            "royale_car_block",
            "royale_car_blocks_transport",
            "royale_car_blogger",
            "royale_car_braided",
            "royale_car_bugs_harvester",
            "royale_car_carr_of_rg",
            "royale_car_circus_racer",
            "royale_car_cyber_cop_car",
            "royale_car_deville_1977",
            "royale_car_diver_3000",
            "royale_car_duck",
            "royale_car_exub_drag",
            "royale_car_festive_tractor",
            "royale_car_flamy_racer",
            "royale_car_floating_water_lily",
            "royale_car_flying_dragon",
            "royale_car_ghost_coffin_kart",
            "royale_car_grave",
            "royale_car_heavy_rover",
            "royale_car_high_intelligent",
            "royale_car_irriadiated_taxi",
            "royale_car_lands_walker",
            "royale_car_laser_bunny",
            "royale_car_mining_transport",
            "royale_car_mobile_kitchen",
            "royale_car_monster_truck",
            "royale_car_moon_princess_carriage",
            "royale_car_moonstrider",
            "royale_car_motorcycle_phoenix",
            "royale_car_mutated_limps",
            "royale_car_mysterious_carriage",
            "royale_car_passenger_beetle",
            "royale_car_patrol",
            "royale_car_quicksilver",
            "royale_car_robbeep_beep",
            "royale_car_robot_carrier",
            "royale_car_santas_autonomic_sleigh",
            "royale_car_secret_explorer",
            "royale_car_siege_ram",
            "royale_car_snow_spirit_carrier",
            "royale_car_space_traveller",
            "royale_car_space_travelling",
            "royale_car_steam",
            "royale_car_stonecutter",
            "royale_car_stormtroopers_truck",
            "royale_car_summer_van",
            "royale_car_survivors",
            "royale_car_sweeper_z",
            "royale_car_train",
            "royale_car_trojan_horse",
            "royale_car_vacations_minivan",
            "royale_car_village_keeper",
            "royale_car_winter_carriage",
            "royale_car_yorkshire_buggy",
            "royale_jet_scooter",
            "royale_road_warrior",
            "royale_snowmobile",
            "royale_snowmobile_freeplay"
    };
        const char* PetList[101] = {
            "pet_cat",
            "pet_dog",
            "pet_parrot",
            "pet_rabbit",
            "pet_cat_2",
            "pet_dachshund",
            "pet_goat",
            "pet_cat_3",
            "pet_bat",
            "pet_fox",
            "pet_penguin",
            "pet_wolf",
            "pet_sheep",
            "pet_raccoon",
            "pet_husky",
            "pet_boar",
            "pet_ram",
            "pet_crab",
            "pet_owl",
            "pet_snake",
            "pet_lion",
            "pet_panda",
            "pet_red_panda",
            "pet_tukan",
            "pet_meerkat",
            "pet_robo_dog",
            "pet_porcupine",
            "pet_zombiecat",
            "pet_eagle",
            "pet_deer",
            "pet_polarbear",
            "pet_monkey",
            "pet_alien_cat",
            "pet_bear",
            "pet_hyena",
            "pet_kangaroo",
            "pet_skunk",
            "pet_ostrich",
            "pet_pterodactyl",
            "pet_dinosaur",
            "pet_arnold_3000",
            "pet_chicken",
            "pet_paradehorse",
            "pet_rhino",
            "pet_tiger",
            "pet_panther",
            "pet_horse",
            "pet_unicorn",
            "pet_phoenix",
            "pet_magical_dragon",
            "pet_griffin",
            "pet_eaglespirit",
            "pet_mammoth",
            "pet_sabertooth_tiger",
            "pet_raven",
            "pet_trex",
            "pet_cyberphoenix",
            "pet_blocston_dogmatics",
            "pet_turkey",
            "pet_armadillo",
            "pet_griffin_owl",
            "pet_squirrel",
            "pet_tactical_ferret",
            "pet_stone_elemental",
            "pet_fighting_turtle",
            "pet_knitted_pony",
            "pet_stone",
            "pet_horse_figure",
            "pet_lucky_duck",
            "pet_green_novice",
            "pet_headbug",
            "pet_chick01",
            "pet_pocket_demon",
            "pet_flappy_fish",
            "pet_zazou",
            "pet_pga_statue",
            "pet_vacuum_helpbro_2000",
            "pet_ice_dragon_egg",
            "pet_combat_robb_e",
            "pet_small_floppa",
            "pet_sacred_scarab",
            "pet_mecha_cat",
            "pet_zombie_head",
            "pet_support_piglet",
            "pet_firefly_cat",
            "pet_elementals_helper",
            "pet_tankmouse",
            "pet_backwater_dweller",
            "pet_shiny_companion",
            "pet_8_bit_boi",
            "pet_blue_buddy",
            "pet_wise_owl",
            "pet_stingray_3000",
            "pet_bullfinch_the_giver",
            "pet_festive_black_rabbit",
            "pet_servants_right_hand",
            "pet_ice_cream_cup",
            "pet_anniversary_kitty",
            "pet_capy",
            "pet_modified_assistant",
            "pet_cheering_up_cookie"
        };
};

extern Backend RunBackend;